/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mega_wifidisplay_WifiDisplaySource */

#ifndef _Included_com_mega_wifidisplay_WifiDisplaySource
#define _Included_com_mega_wifidisplay_WifiDisplaySource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mega_wifidisplay_WifiDisplaySource
 * Method:    setServer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySource_setServer
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySource
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySource_setSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySource
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySource_start
  (JNIEnv *, jclass);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySource
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySource_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
