/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mega_wifidisplay_WifiDisplaySink */

#ifndef _Included_com_mega_wifidisplay_WifiDisplaySink
#define _Included_com_mega_wifidisplay_WifiDisplaySink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mega_wifidisplay_WifiDisplaySink
 * Method:    setSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySink_setSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySink
 * Method:    setVideoConfig
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySink_setVideoConfig
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySink
 * Method:    setServer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySink_setServer
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySink
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySink_start
  (JNIEnv *, jclass);

/*
 * Class:     com_mega_wifidisplay_WifiDisplaySink
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mega_wifidisplay_WifiDisplaySink_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
